import { TimeZone } from '../models/base.model';

export const GlobalTimeZone =
    {
        // TimeZones:
        // [
        //     { decimaloffset: "+10.50", abbr: "ACDT", zonename: "Australian Central Daylight Savings Time", utcoffset: "UTC+10:30" },
        //     { decimaloffset: "+09.50", abbr: "ACST", zonename: "Australian Central Standard Time", utcoffset: "UTC+09:30" },
        //     { decimaloffset: "-05", abbr: "ACT", zonename: "Acre Time", utcoffset: "UTC-05" },
        //     { decimaloffset: "-03", abbr: "ADT", zonename: "Atlantic Daylight Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+11", abbr: "AEDT", zonename: "Australian Eastern Daylight Savings Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+10", abbr: "AEST", zonename: "Australian Eastern Standard Time", utcoffset: "UTC+10" },
        //     { decimaloffset: "+4.5", abbr: "AFT", zonename: "Afghanistan Time", utcoffset: "UTC+04:30" },
        //     { decimaloffset: "-08", abbr: "AKDT", zonename: "Alaska Daylight Time", utcoffset: "UTC-08" },
        //     { decimaloffset: "-09", abbr: "AKST", zonename: "Alaska Standard Time", utcoffset: "UTC-09" },
        //     { decimaloffset: "-03", abbr: "AMST", zonename: "Amazon Summer Time (Brazil)", utcoffset: "UTC-03" },
        //     { decimaloffset: "-04", abbr: "AMT", zonename: "Amazon Time (Brazil)", utcoffset: "UTC-04" },
        //     { decimaloffset: "+04", abbr: "AMT", zonename: "Armenia Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "-03", abbr: "ART", zonename: "Argentina Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+03", abbr: "AST", zonename: "Arabia Standard Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "-04", abbr: "AST", zonename: "Atlantic Standard Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "+08", abbr: "AWST", zonename: "Australian Western Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "00", abbr: "AZOST", zonename: "Azores Summer Time", utcoffset: "UTC±00" },
        //     { decimaloffset: "-01", abbr: "AZOT", zonename: "Azores Standard Time", utcoffset: "UTC-01" },
        //     { decimaloffset: "+04", abbr: "AZT", zonename: "Azerbaijan Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "+08", abbr: "BDT", zonename: "Brunei Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+06", abbr: "BIOT", zonename: "British Indian Ocean Time", utcoffset: "UTC+06" },
        //     { decimaloffset: "-12", abbr: "BIT", zonename: "Baker Island Time", utcoffset: "UTC-12" },
        //     { decimaloffset: "-04", abbr: "BOT", zonename: "Bolivia Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "-02", abbr: "BRST", zonename: "Brasilia Summer Time", utcoffset: "UTC-02" },
        //     { decimaloffset: "-03", abbr: "BRT", zonename: "Brasilia Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+06", abbr: "BST", zonename: "Bangladesh Standard Time", utcoffset: "UTC+06" },
        //     { decimaloffset: "+11", abbr: "BST", zonename: "Bougainville Standard Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+01", abbr: "BST", zonename: "British Summer Time", utcoffset: "UTC+01" },
        //     { decimaloffset: "+06", abbr: "BTT", zonename: "Bhutan Time", utcoffset: "UTC+06" },
        //     { decimaloffset: "+02", abbr: "CAT", zonename: "Central Africa Time", utcoffset: "UTC+02" },
        //     { decimaloffset: "+06.50", abbr: "CCT", zonename: "Cocos Islands Time", utcoffset: "UTC+06:30" },
        //     { decimaloffset: "-05", abbr: "CDT", zonename: "Central Daylight Time (North America)", utcoffset: "UTC-05" },
        //     { decimaloffset: "-04", abbr: "CDT", zonename: "Cuba Daylight Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "+02", abbr: "CEST", zonename: "Central European Summer Time (Cf. HAEC)", utcoffset: "UTC+02" },
        //     { decimaloffset: "+01", abbr: "CET", zonename: "Central European Time", utcoffset: "UTC+01" },
        //     { decimaloffset: "+13.75", abbr: "CHADT", zonename: "Chatham Daylight Time", utcoffset: "UTC+13:45" },
        //     { decimaloffset: "+12.75", abbr: "CHAST", zonename: "Chatham Standard Time", utcoffset: "UTC+12:45" },
        //     { decimaloffset: "+08", abbr: "CHOT", zonename: "Choibalsan Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+09", abbr: "CHOST", zonename: "Choibalsan Summer Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "+10", abbr: "CHST", zonename: "Chamorro Standard Time", utcoffset: "UTC+10" },
        //     { decimaloffset: "+10", abbr: "CHUT", zonename: "Chuuk Time", utcoffset: "UTC+10" },
        //     { decimaloffset: "-08", abbr: "CIST", zonename: "Clipperton Island Standard Time", utcoffset: "UTC-08" },
        //     { decimaloffset: "+08", abbr: "CIT", zonename: "Central Indonesia Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "-10", abbr: "CKT", zonename: "Cook Island Time", utcoffset: "UTC-10" },
        //     { decimaloffset: "-03", abbr: "CLST", zonename: "Chile Summer Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "-04", abbr: "CLT", zonename: "Chile Standard Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "-04", abbr: "COST", zonename: "Colombia Summer Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "-05", abbr: "COT", zonename: "Colombia Time", utcoffset: "UTC-05" },
        //     { decimaloffset: "-06", abbr: "CST", zonename: "Central Standard Time (North America)", utcoffset: "UTC-06" },
        //     { decimaloffset: "+08", abbr: "CST", zonename: "China Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+09.50", abbr: "ACST", zonename: "Central Standard Time (Australia)", utcoffset: "UTC+09:30" },
        //     { decimaloffset: "+10.50", abbr: "ACDT", zonename: "Central Summer Time (Australia)", utcoffset: "UTC+10:30" },
        //     { decimaloffset: "-05", abbr: "CST", zonename: "Cuba Standard Time", utcoffset: "UTC-05" },
        //     { decimaloffset: "+08", abbr: "CT", zonename: "China time", utcoffset: "UTC+08" },
        //     { decimaloffset: "-01", abbr: "CVT", zonename: "Cape Verde Time", utcoffset: "UTC-01" },
        //     { decimaloffset: "+08.75", abbr: "CWST", zonename: "Central Western Standard Time (Australia) unofficial", utcoffset: "UTC+08:45" },
        //     { decimaloffset: "+07", abbr: "CXT", zonename: "Christmas Island Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+07", abbr: "DAVT", zonename: "Davis Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+10", abbr: "DDUT", zonename: "Dumont d'Urville Time", utcoffset: "UTC+10" },
        //     { decimaloffset: "+01", abbr: "DFT", zonename: "AIX specific equivalent of Central European Time", utcoffset: "UTC+01" },
        //     { decimaloffset: "-05", abbr: "EASST", zonename: "Easter Island Summer Time", utcoffset: "UTC-05" },
        //     { decimaloffset: "-06", abbr: "EAST", zonename: "Easter Island Standard Time", utcoffset: "UTC-06" },
        //     { decimaloffset: "+03", abbr: "EAT", zonename: "East Africa Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "-04", abbr: "ECT", zonename: "Eastern Caribbean Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "-05", abbr: "ECT", zonename: "Ecuador Time", utcoffset: "UTC-05" },
        //     { decimaloffset: "-04", abbr: "EDT", zonename: "Eastern Daylight Time (North America)", utcoffset: "UTC-04" },
        //     { decimaloffset: "+11", abbr: "AEDT", zonename: "Eastern Summer Time (Australia)", utcoffset: "UTC+11" },
        //     { decimaloffset: "+03", abbr: "EEST", zonename: "Eastern European Summer Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "+02", abbr: "EET", zonename: "Eastern European Time", utcoffset: "UTC+02" },
        //     { decimaloffset: "00", abbr: "EGST", zonename: "Eastern Greenland Summer Time", utcoffset: "UTC±00" },
        //     { decimaloffset: "-01", abbr: "EGT", zonename: "Eastern Greenland Time", utcoffset: "UTC-01" },
        //     { decimaloffset: "+09", abbr: "EIT", zonename: "Eastern Indonesian Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "-05", abbr: "EST", zonename: "Eastern Standard Time (North America)", utcoffset: "UTC-05" },
        //     { decimaloffset: "+10", abbr: "AEST", zonename: "Eastern Standard Time (Australia)", utcoffset: "UTC+10" },
        //     { decimaloffset: "+03", abbr: "FET", zonename: "Further-eastern European Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "+12", abbr: "FJT", zonename: "Fiji Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "-03", abbr: "FKST", zonename: "Falkland Islands Summer Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "-04", abbr: "FKT", zonename: "Falkland Islands Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "-02", abbr: "FNT", zonename: "Fernando de Noronha Time", utcoffset: "UTC-02" },
        //     { decimaloffset: "-06", abbr: "GALT", zonename: "Galapagos Time", utcoffset: "UTC-06" },
        //     { decimaloffset: "-09", abbr: "GAMT", zonename: "Gambier Islands", utcoffset: "UTC-09" },
        //     { decimaloffset: "+04", abbr: "GET", zonename: "Georgia Standard Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "-03", abbr: "GFT", zonename: "French Guiana Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+12", abbr: "GILT", zonename: "Gilbert Island Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "-09", abbr: "GIT", zonename: "Gambier Island Time", utcoffset: "UTC-09" },
        //     { decimaloffset: "00", abbr: "GMT", zonename: "Greenwich Mean Time", utcoffset: "UTC±00" },
        //     { decimaloffset: "-02", abbr: "GST", zonename: "South Georgia and the South Sandwich Islands", utcoffset: "UTC-02" },
        //     { decimaloffset: "+04", abbr: "GST", zonename: "Gulf Standard Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "-04", abbr: "GYT", zonename: "Guyana Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "-09", abbr: "HADT", zonename: "Hawaii-Aleutian Daylight Time", utcoffset: "UTC-09" },
        //     { decimaloffset: "+02", abbr: "HAEC", zonename: "Heure Avancée d'Europe Centrale francised name for CEST", utcoffset: "UTC+02" },
        //     { decimaloffset: "-10", abbr: "HAST", zonename: "Hawaii-Aleutian Standard Time", utcoffset: "UTC-10" },
        //     { decimaloffset: "+08", abbr: "HKT", zonename: "Hong Kong Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+05", abbr: "HMT", zonename: "Heard and McDonald Islands Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "+08", abbr: "HOVST", zonename: "Khovd Summer Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+07", abbr: "HOVT", zonename: "Khovd Standard Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+07", abbr: "ICT", zonename: "Indochina Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+03", abbr: "IDT", zonename: "Israel Daylight Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "+03", abbr: "IOT", zonename: "Indian Ocean Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "+04.50", abbr: "IRDT", zonename: "Iran Daylight Time", utcoffset: "UTC+04:30" },
        //     { decimaloffset: "+08", abbr: "IRKT", zonename: "Irkutsk Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+03.50", abbr: "IRST", zonename: "Iran Standard Time", utcoffset: "UTC+03:30" },
        //     { decimaloffset: "+05.50", abbr: "IST", zonename: "Indian Standard Time", utcoffset: "UTC+05:30" },
        //     { decimaloffset: "+01", abbr: "IST", zonename: "Irish Standard Time", utcoffset: "UTC+01" },
        //     { decimaloffset: "+02", abbr: "IST", zonename: "Israel Standard Time", utcoffset: "UTC+02" },
        //     { decimaloffset: "+09", abbr: "JST", zonename: "Japan Standard Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "+06", abbr: "KGT", zonename: "Kyrgyzstan time", utcoffset: "UTC+06" },
        //     { decimaloffset: "+11", abbr: "KOST", zonename: "Kosrae Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+07", abbr: "KRAT", zonename: "Krasnoyarsk Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+09", abbr: "KST", zonename: "Korea Standard Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "+10.50", abbr: "LHST", zonename: "Lord Howe Standard Time", utcoffset: "UTC+10:30" },
        //     { decimaloffset: "+11", abbr: "LHST", zonename: "Lord Howe Summer Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+14", abbr: "LINT", zonename: "Line Islands Time", utcoffset: "UTC+14" },
        //     { decimaloffset: "+12", abbr: "MAGT", zonename: "Magadan Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "-09.50", abbr: "MART", zonename: "Marquesas Islands Time", utcoffset: "UTC-09:30" },
        //     { decimaloffset: "+05", abbr: "MAWT", zonename: "Mawson Station Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "-06", abbr: "MDT", zonename: "Mountain Daylight Time (North America)", utcoffset: "UTC-06" },
        //     { decimaloffset: "+01", abbr: "MET", zonename: "Middle European Time Same zone as CET", utcoffset: "UTC+01" },
        //     { decimaloffset: "+02", abbr: "MEST", zonename: "Middle European Summer Time Same zone as CEST", utcoffset: "UTC+02" },
        //     { decimaloffset: "+12", abbr: "MHT", zonename: "Marshall Islands", utcoffset: "UTC+12" },
        //     { decimaloffset: "+11", abbr: "MIST", zonename: "Macquarie Island Station Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "-09.50", abbr: "MIT", zonename: "Marquesas Islands Time", utcoffset: "UTC-09:30" },
        //     { decimaloffset: "+06.50", abbr: "MMT", zonename: "Myanmar Standard Time", utcoffset: "UTC+06:30" },
        //     { decimaloffset: "+03", abbr: "MSK", zonename: "Moscow Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "+08", abbr: "MST", zonename: "Malaysia Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "-07", abbr: "MST", zonename: "Mountain Standard Time (North America)", utcoffset: "UTC-07" },
        //     { decimaloffset: "+04", abbr: "MUT", zonename: "Mauritius Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "+05", abbr: "MVT", zonename: "Maldives Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "+08", abbr: "MYT", zonename: "Malaysia Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+11", abbr: "NCT", zonename: "New Caledonia Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "-02.50", abbr: "NDT", zonename: "Newfoundland Daylight Time", utcoffset: "UTC-02:30" },
        //     { decimaloffset: "+11", abbr: "NFT", zonename: "Norfolk Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+05.75", abbr: "NPT", zonename: "Nepal Time", utcoffset: "UTC+05:45" },
        //     { decimaloffset: "-03.50", abbr: "NST", zonename: "Newfoundland Standard Time", utcoffset: "UTC-03:30" },
        //     { decimaloffset: "-03.50", abbr: "NT", zonename: "Newfoundland Time", utcoffset: "UTC-03:30" },
        //     { decimaloffset: "-11", abbr: "NUT", zonename: "Niue Time", utcoffset: "UTC-11" },
        //     { decimaloffset: "+13", abbr: "NZDT", zonename: "New Zealand Daylight Time", utcoffset: "UTC+13" },
        //     { decimaloffset: "+12", abbr: "NZST", zonename: "New Zealand Standard Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "+06", abbr: "OMST", zonename: "Omsk Time", utcoffset: "UTC+06" },
        //     { decimaloffset: "+05", abbr: "ORAT", zonename: "Oral Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "-07", abbr: "PDT", zonename: "Pacific Daylight Time (North America)", utcoffset: "UTC-07" },
        //     { decimaloffset: "-05", abbr: "PET", zonename: "Peru Time", utcoffset: "UTC-05" },
        //     { decimaloffset: "+12", abbr: "PETT", zonename: "Kamchatka Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "+10", abbr: "PGT", zonename: "Papua New Guinea Time", utcoffset: "UTC+10" },
        //     { decimaloffset: "+13", abbr: "PHOT", zonename: "Phoenix Island Time", utcoffset: "UTC+13" },
        //     { decimaloffset: "+08", abbr: "PHT", zonename: "Philippine Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+05", abbr: "PKT", zonename: "Pakistan Standard Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "-02", abbr: "PMDT", zonename: "Saint Pierre and Miquelon Daylight time", utcoffset: "UTC-02" },
        //     { decimaloffset: "-03", abbr: "PMST", zonename: "Saint Pierre and Miquelon Standard Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+11", abbr: "PONT", zonename: "Pohnpei Standard Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "-08", abbr: "PST", zonename: "Pacific Standard Time (North America)", utcoffset: "UTC-08" },
        //     { decimaloffset: "+08", abbr: "PST", zonename: "Philippine Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "-03", abbr: "PYST", zonename: "Paraguay Summer Time (South America)", utcoffset: "UTC-03" },
        //     { decimaloffset: "-04", abbr: "PYT", zonename: "Paraguay Time (South America)", utcoffset: "UTC-04" },
        //     { decimaloffset: "+04", abbr: "RET", zonename: "Réunion Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "-03", abbr: "ROTT", zonename: "Rothera Research Station Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+11", abbr: "SAKT", zonename: "Sakhalin Island time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+04", abbr: "SAMT", zonename: "Samara Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "+02", abbr: "SAST", zonename: "South African Standard Time", utcoffset: "UTC+02" },
        //     { decimaloffset: "+11", abbr: "SBT", zonename: "Solomon Islands Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+04", abbr: "SCT", zonename: "Seychelles Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "-10", abbr: "SDT", zonename: "Samoa Daylight Time", utcoffset: "UTC-10" },
        //     { decimaloffset: "+08", abbr: "SGT", zonename: "Singapore Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+05.50", abbr: "SLST", zonename: "Sri Lanka Standard Time", utcoffset: "UTC+05:30" },
        //     { decimaloffset: "+11", abbr: "SRET", zonename: "Srednekolymsk Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "-03", abbr: "SRT", zonename: "Suriname Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "-11", abbr: "SST", zonename: "Samoa Standard Time", utcoffset: "UTC-11" },
        //     { decimaloffset: "+08", abbr: "SST", zonename: "Singapore Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+03", abbr: "SYOT", zonename: "Showa Station Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "-10", abbr: "TAHT", zonename: "Tahiti Time", utcoffset: "UTC-10" },
        //     { decimaloffset: "+07", abbr: "THA", zonename: "Thailand Standard Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+05", abbr: "TFT", zonename: "Indian/Kerguelen", utcoffset: "UTC+05" },
        //     { decimaloffset: "+05", abbr: "TJT", zonename: "Tajikistan Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "+13", abbr: "TKT", zonename: "Tokelau Time", utcoffset: "UTC+13" },
        //     { decimaloffset: "+09", abbr: "TLT", zonename: "Timor Leste Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "+05", abbr: "TMT", zonename: "Turkmenistan Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "+03", abbr: "TRT", zonename: "Turkey Time", utcoffset: "UTC+03" },
        //     { decimaloffset: "+13", abbr: "TOT", zonename: "Tonga Time", utcoffset: "UTC+13" },
        //     { decimaloffset: "+12", abbr: "TVT", zonename: "Tuvalu Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "+09", abbr: "ULAST", zonename: "Ulaanbaatar Summer Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "+08", abbr: "ULAT", zonename: "Ulaanbaatar Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+02", abbr: "USZ1", zonename: "Kaliningrad Time", utcoffset: "UTC+02" },
        //     { decimaloffset: "0", abbr: "UTC", zonename: "Coordinated Universal Time", utcoffset: "UTC±00" },
        //     { decimaloffset: "-02", abbr: "UYST", zonename: "Uruguay Summer Time", utcoffset: "UTC-02" },
        //     { decimaloffset: "-03", abbr: "UYT", zonename: "Uruguay Standard Time", utcoffset: "UTC-03" },
        //     { decimaloffset: "+05", abbr: "UZT", zonename: "Uzbekistan Time", utcoffset: "UTC+05" },
        //     { decimaloffset: "-04", abbr: "VET", zonename: "Venezuelan Standard Time", utcoffset: "UTC-04" },
        //     { decimaloffset: "+10", abbr: "VLAT", zonename: "Vladivostok Time", utcoffset: "UTC+10" },
        //     { decimaloffset: "+04", abbr: "VOLT", zonename: "Volgograd Time", utcoffset: "UTC+04" },
        //     { decimaloffset: "+06", abbr: "VOST", zonename: "Vostok Station Time", utcoffset: "UTC+06" },
        //     { decimaloffset: "+11", abbr: "VUT", zonename: "Vanuatu Time", utcoffset: "UTC+11" },
        //     { decimaloffset: "+12", abbr: "WAKT", zonename: "Wake Island Time", utcoffset: "UTC+12" },
        //     { decimaloffset: "+02", abbr: "WAST", zonename: "West Africa Summer Time", utcoffset: "UTC+02" },
        //     { decimaloffset: "+01", abbr: "WAT", zonename: "West Africa Time", utcoffset: "UTC+01" },
        //     { decimaloffset: "+01", abbr: "WEST", zonename: "Western European Summer Time", utcoffset: "UTC+01" },
        //     { decimaloffset: "±00", abbr: "WET", zonename: "Western European Time", utcoffset: "UTC±00" },
        //     { decimaloffset: "+07", abbr: "WIT", zonename: "Western Indonesian Time", utcoffset: "UTC+07" },
        //     { decimaloffset: "+08", abbr: "WST", zonename: "Western Standard Time", utcoffset: "UTC+08" },
        //     { decimaloffset: "+09", abbr: "YAKT", zonename: "Yakutsk Time", utcoffset: "UTC+09" },
        //     { decimaloffset: "+05", abbr: "YEKT", zonename: "Yekaterinburg Time", utcoffset: "UTC+05" }
        // ] as TimeZone[]
        TimeZones:
        [
            { decimaloffset: "-12.00", abbr: "ACDT", zonename: "(UTC-12:00) International Date Line West", utcoffset: "UTC-12:00" },
            { decimaloffset: "-11.00", abbr: "ACST", zonename: "(UTC-11:00) Coordinated Universal Time-11", utcoffset: "UTC-11:00" },
            { decimaloffset: "-10.00", abbr: "ACT", zonename: "(UTC-10:00) Hawaii", utcoffset: "UTC-10:00" },
            { decimaloffset: "-9.00", abbr: "ADT", zonename: "(UTC-09:00) Alaska", utcoffset: "UTC-09:00" },
            { decimaloffset: "-8.00", abbr: "AEDT", zonename: "(UTC-08:00) Baja California", utcoffset: "UTC-08:00" },
            { decimaloffset: "-8.00", abbr: "AEST", zonename: "(UTC-08:00) Pacific Time (US & Canada)", utcoffset: "UTC-08:00" },
            { decimaloffset: "-7.00", abbr: "AFT", zonename: "(UTC-07:00) Arizona", utcoffset: "UTC-07:00" },
            { decimaloffset: "-7.00", abbr: "AKDT", zonename: "(UTC-07:00) Chihuahua, La Paz, Mazatlan", utcoffset: "UTC-07:00" },
            { decimaloffset: "-7.00", abbr: "AKST", zonename: "(UTC-07:00) Mountain Time (US & Canada)", utcoffset: "UTC-07:00)" },
            { decimaloffset: "-06.00", abbr: "AMST", zonename: "(UTC-06:00) Central America", utcoffset: "UTC-06:00" },
            { decimaloffset: "-06.00", abbr: "AMT", zonename: "(UTC-06:00) Central Time (US & Canada)", utcoffset: "UTC-06:00" },
            { decimaloffset: "-06.00", abbr: "AMT", zonename: "(UTC-06:00) Guadalajara, Mexico City, Monterrey", utcoffset: "UTC-06:00" },
            { decimaloffset: "-06.00", abbr: "ART", zonename: "(UTC-06:00) Saskatchewan", utcoffset: "UTC-06:00" },
            { decimaloffset: "-05.00", abbr: "AST", zonename: "(UTC-05:00) Bogota, Lima, Quito", utcoffset: "UTC-05:00" },
            { decimaloffset: "-05.00", abbr: "AST", zonename: "(UTC-05:00) Eastern Time (US & Canada)", utcoffset: "UTC-05:00" },
            { decimaloffset: "-05.00", abbr: "AWST", zonename: "(UTC-05:00) Indiana (East)", utcoffset: "UTC-05:00" },
            { decimaloffset: "-04.50", abbr: "AZOST", zonename: "(UTC-04:30) Caracas", utcoffset: "UTC-04:30" },
            { decimaloffset: "-04.00", abbr: "AZOT", zonename: "(UTC-04:00) Asuncion", utcoffset: "UTC-04:00" },
            { decimaloffset: "-04.00", abbr: "AZT", zonename: "(UTC-04:00) Atlantic Time (Canada)", utcoffset: "UTC-04:00" },
            { decimaloffset: "-04.00", abbr: "BDT", zonename: "(UTC-04:00) Cuiaba", utcoffset: "UTC-04:00" },
            { decimaloffset: "-04.00", abbr: "BIOT", zonename: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan", utcoffset: "UTC-04:00" },
            { decimaloffset: "-04.00", abbr: "BIT", zonename: "(UTC-04:00) Santiago", utcoffset: "UTC-04:00" },
            { decimaloffset: "-03.50", abbr: "BOT", zonename: "(UTC-03:30) Newfoundland", utcoffset: "UTC-03:30" },
            { decimaloffset: "-03.00", abbr: "BRST", zonename: "(UTC-03:00) Brasilia", utcoffset: "UTC-03:00" },
            { decimaloffset: "-03.00", abbr: "BRT", zonename: "(UTC-03:00) Buenos Aires", utcoffset: "UTC-03:00" },
            { decimaloffset: "-03.00", abbr: "BST", zonename: "(UTC-03:00) Cayenne, Fortaleza", utcoffset: "UTC-03:00" },
            { decimaloffset: "-03.00", abbr: "BST", zonename: "(UTC-03:00) Greenland", utcoffset: "UTC-03:00" },
            { decimaloffset: "-03.00", abbr: "BST", zonename: "(UTC-03:00) Montevideo", utcoffset: "UTC-03:00" },
            { decimaloffset: "-03.00", abbr: "BTT", zonename: "(UTC-03:00) Salvador", utcoffset: "UTC-03:00" },
            { decimaloffset: "-02.00", abbr: "CAT", zonename: "(UTC-02:00) Coordinated Universal Time-02", utcoffset: "UTC-03:00" },
            { decimaloffset: "-02.00", abbr: "CCT", zonename: "(UTC-02:00) Mid-Atlantic - Old", utcoffset: "UTC-02:00" },
            { decimaloffset: "-01.00", abbr: "CDT", zonename: "(UTC-01:00) Azores", utcoffset: "UTC-01:00" },
            { decimaloffset: "-01.00", abbr: "CDT", zonename: "(UTC-01:00) Cape Verde Is.", utcoffset: "UTC-01:00" },
            { decimaloffset: "00", abbr: "CEST", zonename: "(UTC) Casablanca", utcoffset: "UTC±00" },
            { decimaloffset: "00", abbr: "CET", zonename: "(UTC) Coordinated Universal Time", utcoffset: "UTC±00" },
            { decimaloffset: "00", abbr: "CHADT", zonename: "(UTC) Dublin, Edinburgh, Lisbon, London", utcoffset: "UTC±00" },
            { decimaloffset: "00", abbr: "CHAST", zonename: "(UTC) Monrovia, Reykjavik", utcoffset: "UTC±00" },
            { decimaloffset: "+01.00", abbr: "CHOT", zonename: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", utcoffset: "UTC+01:00" },
            { decimaloffset: "+01.00", abbr: "CHOST", zonename: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague", utcoffset: "UTC+01:00" },
            { decimaloffset: "+01.00", abbr: "CHST", zonename: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris", utcoffset: "UTC+01:00" },
            { decimaloffset: "+01.00", abbr: "CHUT", zonename: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb", utcoffset: "UTC+01:00" },
            { decimaloffset: "+01.00", abbr: "CIST", zonename: "(UTC+01:00) West Central Africa", utcoffset: "UTC+01:00" },
            { decimaloffset: "+01.00", abbr: "CIT", zonename: "(UTC+01:00) Windhoek", utcoffset: "UTC+01:00" },
            { decimaloffset: "+02.00", abbr: "CKT", zonename: "(UTC+02:00) Athens, Bucharest", utcoffset: "UTC+02.00" },
            { decimaloffset: "+02.00", abbr: "CLST", zonename: "(UTC+02:00) Beirut", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "CLT", zonename: "(UTC+02:00) Cairo", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "COST", zonename: "(UTC+02:00) Damascus", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "COT", zonename: "(UTC+02:00) E. Europe", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "CST", zonename: "(UTC+02:00) Harare, Pretoria", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "CST", zonename: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "ACST", zonename: "(UTC+02:00) Istanbul", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "ACDT", zonename: "(UTC+02:00) Jerusalem", utcoffset: "UTC+02:00" },
            { decimaloffset: "+02.00", abbr: "CST", zonename: "(UTC+02:00) Tripoli", utcoffset: "UTC+02:00" },
            { decimaloffset: "+03.00", abbr: "CT", zonename: "(UTC+03:00) Amman", utcoffset: "UTC+03:00" },
            { decimaloffset: "+03.00", abbr: "CVT", zonename: "(UTC+03:00) Baghdad", utcoffset: "UTC+03:00" },
            { decimaloffset: "+03.00", abbr: "CWST", zonename: "(UTC+03:00) Kaliningrad, Minsk", utcoffset: "UTC+03:00" },
            { decimaloffset: "+03.00", abbr: "CXT", zonename: "(UTC+03:00) Kuwait, Riyadh", utcoffset: "UTC+03:00" },
            { decimaloffset: "+03.00", abbr: "DAVT", zonename: "(UTC+03:00) Nairobi", utcoffset: "UTC+03:00" },
            { decimaloffset: "+03.50", abbr: "DDUT", zonename: "(UTC+03:30) Tehran", utcoffset: "UTC+03:30" },
            { decimaloffset: "+04.00", abbr: "DFT", zonename: "(UTC+04:00) Abu Dhabi, Muscat", utcoffset: "UTC+04:00" },
            { decimaloffset: "+04.00", abbr: "EASST", zonename: "(UTC+04:00) Baku", utcoffset: "UTC+04:00" },
            { decimaloffset: "+04.00", abbr: "EAST", zonename: "(UTC+04:00) Moscow, St. Petersburg, Volgograd", utcoffset: "UTC+04:00" },
            { decimaloffset: "+04.00", abbr: "EAT", zonename: "(UTC+04:00) Port Louis", utcoffset: "UTC+04:00" },
            { decimaloffset: "+04.00", abbr: "ECT", zonename: "(UTC+04:00) Tbilisi", utcoffset: "UTC+04:00" },
            { decimaloffset: "+04.00", abbr: "ECT", zonename: "(UTC+04:00) Yerevan", utcoffset: "UTC+04:00" },
            { decimaloffset: "+04.50", abbr: "EDT", zonename: "(UTC+04:30) Kabul", utcoffset: "UTC+04:30" },
            { decimaloffset: "+05.00", abbr: "AEDT", zonename: "(UTC+05:00) Ashgabat, Tashkent", utcoffset: "UTC+05:00" },
            { decimaloffset: "+05.00", abbr: "EEST", zonename: "(UTC+05:00) Islamabad, Karachi", utcoffset: "UTC+05:00" },
            { decimaloffset: "+05.50", abbr: "EET", zonename: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", utcoffset: "UTC+05:30" },
            { decimaloffset: "+05.50", abbr: "EGST", zonename: "(UTC+05:30) Sri Jayawardenepura", utcoffset: "UTC+05:30" },
            { decimaloffset: "+05.75", abbr: "EGT", zonename: "(UTC+05:45) Kathmandu", utcoffset: "UTC+05:45" },
            { decimaloffset: "+06.00", abbr: "EIT", zonename: "(UTC+06:00) Astana", utcoffset: "UTC+06:00" },
            { decimaloffset: "+06.00", abbr: "EST", zonename: "(UTC+06:00) Dhaka", utcoffset: "UTC+06:00" },
            { decimaloffset: "+06.50", abbr: "AEST", zonename: "(UTC+06:30) Yangon (Rangoon)", utcoffset: "UTC+06:30" },
            { decimaloffset: "+07.00", abbr: "FET", zonename: "(UTC+07:00) Bangkok, Hanoi, Jakarta", utcoffset: "UTC+07:00" },
            { decimaloffset: "+07.00", abbr: "FJT", zonename: "(UTC+07:00) Novosibirsk", utcoffset: "UTC+07:00" },
            { decimaloffset: "+08.00", abbr: "FKST", zonename: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi", utcoffset: "UTC+08:00" },
            { decimaloffset: "+08:00", abbr: "FKT", zonename: "(UTC+08:00) Krasnoyarsk", utcoffset: "UTC+08:00" },
            { decimaloffset: "+08:00", abbr: "FNT", zonename: "(UTC+08:00) Kuala Lumpur, Singapore", utcoffset: "UTC+08:00" },
            { decimaloffset: "+08:00", abbr: "GALT", zonename: "(UTC+08:00) Perth", utcoffset: "UTC+08:00" },
            { decimaloffset: "+08.00", abbr: "GAMT", zonename: "(UTC+08:00) Taipei", utcoffset: "UTC+08:00" },
            { decimaloffset: "+08.00", abbr: "GET", zonename: "(UTC+08:00) Ulaanbaatar", utcoffset: "UTC+09:00" },
            { decimaloffset: "+09.00", abbr: "GFT", zonename: "(UTC+09:00) Irkutsk", utcoffset: "UTC+09:00" },
            { decimaloffset: "+09.00", abbr: "GILT", zonename: "(UTC+09:00) Osaka, Sapporo, Tokyo", utcoffset: "UTC+09:00" },
            { decimaloffset: "+09.00", abbr: "GIT", zonename: "(UTC+09:00) Seoul", utcoffset: "UTC+09:00" },
            { decimaloffset: "+09.50", abbr: "GMT", zonename: "(UTC+09:30) Adelaide", utcoffset: "UTC+09:30" },
            { decimaloffset: "+09.50", abbr: "GST", zonename: "(UTC+09:30) Darwin", utcoffset: "UTC-02" },
            { decimaloffset: "+10.00", abbr: "GST", zonename: "(UTC+10:00) Brisbane", utcoffset: "UTC+10:00" },
            { decimaloffset: "+10.00", abbr: "GYT", zonename: "(UTC+10:00) Canberra, Melbourne, Sydney", utcoffset: "UTC+10:00" },
            { decimaloffset: "+10.00", abbr: "HADT", zonename: "(UTC+10:00) Guam, Port Moresby", utcoffset: "UTC+10:00" },
            { decimaloffset: "+10.00", abbr: "HAEC", zonename: "(UTC+10:00) Hobart", utcoffset: "UTC+10:00" },
            { decimaloffset: "+10.00", abbr: "HAST", zonename: "(UTC+10:00) Yakutsk", utcoffset: "UTC+10:00" },
            { decimaloffset: "+11.00", abbr: "HKT", zonename: "(UTC+11:00) Solomon Is., New Caledonia", utcoffset: "UTC+11:00" },
            { decimaloffset: "+11.00", abbr: "HMT", zonename: "(UTC+11:00) Vladivostok", utcoffset: "UTC+11:00" },
            { decimaloffset: "+12.00", abbr: "HOVST", zonename: "(UTC+12:00) Auckland, Wellington", utcoffset: "UTC+12:00" },
            { decimaloffset: "+12.00", abbr: "HOVT", zonename: "(UTC+12:00) Coordinated Universal Time+12", utcoffset: "UTC+12:00" },
            { decimaloffset: "+12.00", abbr: "ICT", zonename: "(UTC+12:00) Fiji", utcoffset: "UTC+12:00" },
            { decimaloffset: "+12.00", abbr: "IDT", zonename: "(UTC+12:00) Magadan", utcoffset: "UTC+12:00" },
            { decimaloffset: "+12.00", abbr: "IOT", zonename: "(UTC+12:00) Petropavlovsk-Kamchatsky - Old", utcoffset: "UTC+12:00" },
            { decimaloffset: "+12.00", abbr: "IRDT", zonename: "(UTC+13:00) Nuku'alofa", utcoffset: "UTC+13:30" },
            { decimaloffset: "+13.00", abbr: "IRKT", zonename: "(UTC+13:00) Samoa", utcoffset: "UTC+13:00" }
            
        ] as TimeZone[]
    };